export const PAGELAYOUTSECTION__MDT = "PageLayoutSections__mdt";
export const PAGELAYOUTSECTION_BOARDID = 5026697994;
export const PAGELAYOUTSECTION_COLUMN_TITLE_BOARDID = "Board Id";
export const PAGELAYOUTSECTION_COLUMN_TITLE_SECTIONS = "Sections";
export const PAGELAYOUTSECTION_COLUMN_TITLE_SECTIONORDER = "Section Order";
