export const PAGELAYOUTSECTION__MDT = "PageLayoutSections__mdt";
export const USERPROFILE__MDT = "UserProfile__mdt";
export const PAGELAYOUTSECTION_BOARDID = 5026697994;
export const USERPROFILE__MDT_BOARDID = 5026719459;

export const PAGELAYOUTSECTION_COLUMN_TITLE_BOARDID = "Board Id";
export const PAGELAYOUTSECTION_COLUMN_TITLE_SECTIONS = "Sections";
export const PAGELAYOUTSECTION_COLUMN_TITLE_FIELDS = "Fields";
export const PAGELAYOUTSECTION_COLUMN_TITLE_SECTION_RULES = "Section Rules";
export const PAGELAYOUTSECTION_COLUMN_TITLE_SECTIONORDER = "Section Order";


